/**
 * Load the Anchor-generated IDL for the counter spike.
 *
 * The IDL is generated by `anchor build` (target/idl/counter.json) and copied
 * here by the dev workflow (cp target/idl/counter.json app/app/lib/idl.json).
 * In Phase A this replaces itself on every program change.
 */

import type { Idl } from "@coral-xyz/anchor";
import idlJson from "./idl.json";

export const COUNTER_IDL = idlJson as unknown as Idl;

export const COUNTER_PROGRAM_ID =
  process.env.NEXT_PUBLIC_COUNTER_PROGRAM_ID ||
  (typeof idlJson.address === "string" ? idlJson.address : "");

if (!COUNTER_PROGRAM_ID) {
  // eslint-disable-next-line no-console
  console.warn("counter: missing program id; set NEXT_PUBLIC_COUNTER_PROGRAM_ID or rebuild idl.json");
}
