//! `conviction` — Stonk Battles Path A. See ADR 0004 for the per-ix file
//! split + the vendored `anchor-syn` patch that enables it.
//!
//! lib.rs carries the entry point: `declare_id!`, the module graph,
//! 25+26 `pub use` aliases that satisfy anchor-syn's macro-generated
//! path expectations, and the `#[program] mod conviction` block with
//! its forwarders. The 300-LOC cap from CLAUDE.md operating rule #6 is
//! exceeded here; see "File-line cap" note below.

// File-line cap deviation: this entry file is intentionally over 300 LOC.
// The forwarders in `pub mod conviction` are mechanical
// `instructions::<ix>::handler(ctx, …)` calls — they carry the IDL
// discriminators and must stay at crate root because anchor's
// `#[program]` macro emits `crate::instruction::<IxName>::DISCRIMINATOR`
// for the IDL generators that the per-ix handlers reference. All other
// source files are well under 300 LOC — see ADR 0004 for the file layout.

// The `unexpected_cfgs` lint fires for `#[cfg(feature = "solana")]` patterns
// generated by upstream macros (anchor's idl-build path uses RustC's
// target_os-style flag). Allow the lint crate-wide since the upstream macros
// are not ours to silence at the source.
#![allow(unexpected_cfgs)]

use anchor_lang::prelude::*;
use ephemeral_rollups_sdk::anchor::ephemeral;

pub mod state;
pub mod errors;
pub mod constants;
pub mod helpers;
pub mod instructions;

// Re-export every on-chain type so handlers and tests can `use crate::*;`.
pub use errors::*;
pub use state::*;
pub use constants::*;
pub use helpers::*;

// Re-export every Accounts struct at the crate root so `Context<X>` inside
// `#[program]` can identify X via its short name (`CreateMatch`, not
// `instructions::create_match::CreateMatch`). The anchor `ctx_accounts_ident`
// parser at `anchor-syn-1.2.0/src/parser/program/mod.rs:88` extracts
// `path.segments.first().ident` — see ADR 0002 addendum note.
pub use instructions::init_config::InitConfig;
pub use instructions::init_ftr_mint::InitFtrMint;
pub use instructions::create_match::CreateMatch;
pub use instructions::register_team::RegisterTeam;
pub use instructions::lock_in_pre_round::LockInPreRound;
pub use instructions::delegate_match::DelegateMatch;
pub use instructions::delegate_team::DelegateTeam;
pub use instructions::delegate_basket::DelegateBasket;
pub use instructions::delegate_stop_loss::DelegateStopLoss;
pub use instructions::init_basket_permission::InitBasketPermission;
pub use instructions::init_stop_loss_permission::InitStopLossPermission;
pub use instructions::leave_match::LeaveMatch;
pub use instructions::request_villain_vrf::RequestVillainVrf;
pub use instructions::callback_villain::CallbackVillain;
pub use instructions::request_chaos_vrf::RequestChaosVrf;
pub use instructions::callback_chaos::CallbackChaos;
pub use instructions::tick_price::TickPrice;
pub use instructions::reveal_round::RevealRound;
pub use instructions::finalize_round::CommitAndUndelegateMatchState;
pub use instructions::fold::Fold;
pub use instructions::commit_match_state::CommitMatchState;
pub use instructions::propose_param_change::ProposeParamChange;
pub use instructions::vote_on_proposal::VoteOnProposal;
pub use instructions::tally_proposal::TallyProposal;

// Vendor-patch bridge: 26 `pub use ... as __client_accounts_<ix>` aliases.
// anchor-syn 1.2.0 macro emits `pub(crate) mod __client_accounts_<ix>` next
// to each Accounts struct; the vendored patch flips it to `pub` so this
// alias chain works (see ADR 0004).
pub use instructions::init_config::__client_accounts_init_config as __client_accounts_init_config;
pub use instructions::init_ftr_mint::__client_accounts_init_ftr_mint as __client_accounts_init_ftr_mint;
pub use instructions::create_match::__client_accounts_create_match as __client_accounts_create_match;
pub use instructions::register_team::__client_accounts_register_team as __client_accounts_register_team;
pub use instructions::lock_in_pre_round::__client_accounts_lock_in_pre_round as __client_accounts_lock_in_pre_round;
pub use instructions::delegate_match::__client_accounts_delegate_match as __client_accounts_delegate_match;
pub use instructions::delegate_team::__client_accounts_delegate_team as __client_accounts_delegate_team;
pub use instructions::delegate_basket::__client_accounts_delegate_basket as __client_accounts_delegate_basket;
pub use instructions::delegate_stop_loss::__client_accounts_delegate_stop_loss as __client_accounts_delegate_stop_loss;
pub use instructions::init_basket_permission::__client_accounts_init_basket_permission as __client_accounts_init_basket_permission;
pub use instructions::init_stop_loss_permission::__client_accounts_init_stop_loss_permission as __client_accounts_init_stop_loss_permission;
pub use instructions::leave_match::__client_accounts_leave_match as __client_accounts_leave_match;
pub use instructions::request_villain_vrf::__client_accounts_request_villain_vrf as __client_accounts_request_villain_vrf;
pub use instructions::callback_villain::__client_accounts_callback_villain as __client_accounts_callback_villain;
pub use instructions::request_chaos_vrf::__client_accounts_request_chaos_vrf as __client_accounts_request_chaos_vrf;
pub use instructions::callback_chaos::__client_accounts_callback_chaos as __client_accounts_callback_chaos;
pub use instructions::tick_price::__client_accounts_tick_price as __client_accounts_tick_price;
pub use instructions::reveal_round::__client_accounts_reveal_round as __client_accounts_reveal_round;
pub use instructions::finalize_round::__client_accounts_commit_and_undelegate_match_state as __client_accounts_commit_and_undelegate_match_state;
pub use instructions::fold::__client_accounts_fold as __client_accounts_fold;
pub use instructions::commit_match_state::__client_accounts_commit_match_state as __client_accounts_commit_match_state;
pub use instructions::propose_param_change::__client_accounts_propose_param_change as __client_accounts_propose_param_change;
pub use instructions::vote_on_proposal::__client_accounts_vote_on_proposal as __client_accounts_vote_on_proposal;
pub use instructions::tally_proposal::__client_accounts_tally_proposal as __client_accounts_tally_proposal;
// Auto-injected by `#[ephemeral]` — its `__client_accounts_initialize_after_undelegation`
// helper lives inside `pub mod conviction` below; alias it up to the crate root.
pub use conviction::__client_accounts_initialize_after_undelegation as __client_accounts_initialize_after_undelegation;

declare_id!("Fh6bQUgE35Hq7nP22GZ1Youwnph2UaiEh9xTtDJuHJbH");

#[ephemeral]
#[program]
pub mod conviction {
    use super::*;

    pub fn init_config(
        ctx: Context<InitConfig>,
        base_pot: u64,
        round_duration_secs: u32,
        chaos_event_max: u8,
    ) -> Result<()> {
        instructions::init_config::handler(ctx, base_pot, round_duration_secs, chaos_event_max)
    }

    pub fn init_ftr_mint(
        ctx: Context<InitFtrMint>,
        decimals: u8,
    ) -> Result<()> {
        instructions::init_ftr_mint::handler(ctx, decimals)
    }

    pub fn create_match(
        ctx: Context<CreateMatch>,
        match_id: u32,
        pot: u64,
    ) -> Result<()> {
        instructions::create_match::handler(ctx, match_id, pot)
    }

    pub fn register_team(
        ctx: Context<RegisterTeam>,
        match_id: u32,
        side: u8,
        members: Vec<TeamMember>,
    ) -> Result<()> {
        instructions::register_team::handler(ctx, match_id, side, members)
    }

    pub fn lock_in_pre_round(
        ctx: Context<LockInPreRound>,
        _match_id: u32,
        side: u8,
        mints: [Pubkey; 3],
        weights: [u16; 3],
        range: StopLossRange,
        per_member_pubkeys: [Pubkey; 8],
        per_member_flags: [u8; 8],
        per_member_count: u8,
    ) -> Result<()> {
        instructions::lock_in_pre_round::handler(
            ctx, _match_id, side, mints, weights, range, per_member_pubkeys, per_member_flags, per_member_count,
        )
    }

    pub fn delegate_match(
        ctx: Context<DelegateMatch>,
        match_id: u32,
    ) -> Result<()> {
        instructions::delegate_match::handler(ctx, match_id)
    }

    pub fn delegate_team(
        ctx: Context<DelegateTeam>,
        match_id: u32,
        side: u8,
    ) -> Result<()> {
        instructions::delegate_team::handler(ctx, match_id, side)
    }

    pub fn delegate_basket(
        ctx: Context<DelegateBasket>,
        match_id: u32,
        side: u8,
    ) -> Result<()> {
        instructions::delegate_basket::handler(ctx, match_id, side)
    }

    pub fn delegate_stop_loss(
        ctx: Context<DelegateStopLoss>,
        match_id: u32,
        side: u8,
    ) -> Result<()> {
        instructions::delegate_stop_loss::handler(ctx, match_id, side)
    }

    pub fn init_basket_permission(
        ctx: Context<InitBasketPermission>,
    ) -> Result<()> {
        instructions::init_basket_permission::handler(ctx)
    }

    pub fn init_stop_loss_permission(
        ctx: Context<InitStopLossPermission>,
    ) -> Result<()> {
        instructions::init_stop_loss_permission::handler(ctx)
    }

    pub fn leave_match(
        ctx: Context<LeaveMatch>,
        match_id: u32,
        side: u8,
    ) -> Result<()> {
        instructions::leave_match::handler(ctx, match_id, side)
    }

    pub fn request_villain_vrf(
        ctx: Context<RequestVillainVrf>,
        _match_id: u32,
    ) -> Result<()> {
        instructions::request_villain_vrf::handler(ctx, _match_id)
    }

    pub fn callback_villain(
        ctx: Context<CallbackVillain>,
        _match_id: u32,
        randomness: [u8; 32],
    ) -> Result<()> {
        instructions::callback_villain::handler(ctx, _match_id, randomness)
    }

    pub fn request_chaos_vrf(
        ctx: Context<RequestChaosVrf>,
        _match_id: u32,
        sequence: u32,
    ) -> Result<()> {
        instructions::request_chaos_vrf::handler(ctx, _match_id, sequence)
    }

    pub fn callback_chaos(
        ctx: Context<CallbackChaos>,
        _match_id: u32,
        _sequence: u32,
        randomness: [u8; 32],
    ) -> Result<()> {
        instructions::callback_chaos::handler(ctx, _match_id, _sequence, randomness)
    }

    pub fn tick_price(
        ctx: Context<TickPrice>,
        _match_id: u32,
        _mint: Pubkey,
        _price_e6: u64,
    ) -> Result<()> {
        instructions::tick_price::handler(ctx, _match_id, _mint, _price_e6)
    }

    pub fn reveal_round(
        ctx: Context<RevealRound>,
        _match_id: u32,
    ) -> Result<()> {
        instructions::reveal_round::handler(ctx, _match_id)
    }

    pub fn finalize_round(
        ctx: Context<CommitAndUndelegateMatchState>,
        _match_id: u32,
    ) -> Result<()> {
        instructions::finalize_round::handler(ctx, _match_id)
    }

    pub fn fold(
        ctx: Context<Fold>,
        match_id: u32,
        side: u8,
    ) -> Result<()> {
        instructions::fold::handler(ctx, match_id, side)
    }

    pub fn commit_match_state(
        ctx: Context<CommitMatchState>,
    ) -> Result<()> {
        instructions::commit_match_state::handler(ctx)
    }

    pub fn propose_param_change(
        ctx: Context<ProposeParamChange>,
        proposal_id: u32,
        param_name: [u8; 32],
        new_value: u32,
    ) -> Result<()> {
        instructions::propose_param_change::handler(ctx, proposal_id, param_name, new_value)
    }

    pub fn vote_on_proposal(
        ctx: Context<VoteOnProposal>,
        _proposal_id: u32,
        support_yes: bool,
    ) -> Result<()> {
        instructions::vote_on_proposal::handler(ctx, _proposal_id, support_yes)
    }

    pub fn tally_proposal(
        ctx: Context<TallyProposal>,
        _proposal_id: u32,
    ) -> Result<()> {
        instructions::tally_proposal::handler(ctx, _proposal_id)
    }
}
